asilo/urls.py
from django.urls import path

from asilo.api import BackupsDB, ver_detalle_solicitud
from .views import *

app_name= "asilo"
urlpatterns = [
    path("",view=HomeTemplateView.as_view(), name="home"),
    path("recepcion/", view=dashboardRecepcionView.as_view(), name="dashboard-recepcion"),
    path('datos-personales/',view=datosPersonalesCreateView.as_view(), name="datos-personales"),
    path('contacto/<int:pk>/', view=contactoCreateView.as_view(), name="contacto"),
    path('expediente/<int:pk>/', view=expedienteDetailView.as_view(), name="expediente"),
    path("dashboard-medico/", view=medicoGeneralView.as_view(), name="dashboard-medico"),
    path("crear-solicitud/<int:id_expediente>/", view=solicitudCreateView.as_view(), name="crear-solicitud"),
    path("detalle-solicitud/<int:id_solicitud>/",  view=solicitudCitaDetalleCreateView.as_view(), name="detalle-solicitud"),
    path("eliminar-detalle-solicitud/<int:pk>/", view=solicitudDeleteView.as_view(), name="eliminar-detalle-solicitud"),
    path("lista-solicitudes/", view=solicitudesListaView.as_view(), name="lista-solicitudes"),
    path("editar-solicitud/<int:pk>/", view=solicitudCitaDetalleUpdateView.as_view(), name="editar-solicitud"),
    path("crear-backup/", view=BackupsDB.as_view(), name="crear-backup"),
    path("configuraciones/", view=configuracionesView.as_view(), name="configuraciones"),
    path("descargar/<str:nombre>/", view=configuracionesView.descargar_bak, name="descargar"),
    path("eliminar-backup/<str:nombre>/", view=BackupsDB.eliminar_backup, name="eliminar-backup"),
    path("ver-detalle-solicitud/<int:solicitud>/", view=ver_detalle_solicitud.as_view(), name="ver-detalle-solicitud"),
]

fundacion/urls.py
from django.urls import path
from fundacion.views import *


app_name = 'fundacion'


urlpatterns = [
    path('dashboard-medico/', view=dashboardMedico.as_view(), name='dashboard-medico'),
    path('crear-consulta/<int:id_expediente>/', view=consultaMedicaCreateView.as_view(), name='crear-consulta'),
    path("crear-tratamiento/<int:solicitud>/",view=tratamientoCreateView.as_view(), name="crear-tratamiento"),
    path("solicitar-laboratorio/<int:solicitud>/",view=laboratorioSolicitudCreate.as_view(), name="solicitar-laboratorio"),
    path("", view=dashboardRecepcion.as_view(), name="dashboard-recepcion"),
    path("crear-laboratorio/<int:id_solicitudLaboratorio>/", view=examenLaboratorioCreateView.as_view(), name="crear-laboratorio"),
    path("actualizar-laboratorio/<int:pk>/", view=editLaboratorioCreateView.as_view(), name="editar-laboratorio"),
    path("actualizar-detalle-solicitud/<int:pk>/", view=solicitudDetalleUpdateDatetimeView.as_view(), name="actualizar-detalle-solicitud"),
    path("rechazar-solicitud-detalle/<int:pk>/", view=rechazarDetalleRechazarView.as_view(), name='rechazar-solicitud-detalle'),
    path("dashboard-laboratorio/", view=dashboardLaboratorio.as_view(), name="dashboard-laboratorio"),
    path("dashboard-farmacia/", view=dashboardFarmacia.as_view(), name="dashboard-farmacia"),
    path("actualizar-tratamiento/<int:pk>/", view=tratamientoUpdateview.as_view(), name="actualizar-tratamiento"),
    path("fichas/", view=fichasListView.as_view(), name="fichas"),
    path("crear-factura/<int:id_ficha>/", view=facturaCrear.as_view(), name="crear-factura"),
    path("facturas/", view=facturasListView.as_view(), name="facturas"),
    path("enfermedad/<int:solicitud>/", view=enfermedadCreateView.as_view(), name="enfermedad")
]   

# <int:id_cliente>/

settings/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fundacion/', include('fundacion.urls', namespace='fundacion')),
    path('', include('asilo.urls', namespace='asilo')),
    path('usuarios/', include('usuarios.urls', namespace="usuarios")),
    path('contabilidad/',include('contabilidad.urls', namespace="contabilidad")),
    path('reportes/', include('reportes.urls', namespace="reportes")),
    path('api-auth/', include('rest_framework.urls'))
] 
urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fundacion/forms.py
from django import forms

from usuarios.models import empleado
from .models import clienteEnfermedad, consultaMedica, enfermedad,  solicitudCita, solicitudCitaDetalle, solicitudLaboratorio, tratamiento


class consultaMedicaForm( forms.ModelForm):
    class Meta:
        model = consultaMedica
        fields = ["diagnostico"]
        
        
class tratamientoForm( forms.ModelForm):
    class Meta:
        model = tratamiento
        fields = ["medicamento","cantidad", "descripcion"]
    def __init__(self, *args, **kwargs):
        super(tratamientoForm, self).__init__(*args, **kwargs)
        

class solicitudCitaForm(forms.ModelForm):
    pagina = forms.CharField(max_length=10, required=True, widget=forms.HiddenInput())
    class Meta:
        model = solicitudCita
        fields = ["id_enfermero","descripcion"]
        

    def __init__(self, *args, **kwargs):
        super(solicitudCitaForm, self).__init__(*args, **kwargs)
        choices = [(empleado.id_empleado, empleado.id_datos_personales.get_nombreCompleto()) for empleado in  empleado.objects.filter(id_empleado_especialidad__nombre__icontains="Enfermeria")]
        self.fields["id_enfermero"].choices = choices
        self.fields["pagina"].initial = "solicitud"


class solicitudCitaDetalleForm(forms.ModelForm):
    pagina = forms.CharField(max_length=50, required=True, widget=forms.HiddenInput())
    class Meta:
        model = solicitudCitaDetalle
        fields = ["id_especialidad", "descripcion"]


    def __init__(self, *args, **kwargs):
        super(solicitudCitaDetalleForm, self).__init__(*args, **kwargs)
        self.fields["pagina"].initial ="detalle"


class solicitudCitaDetalleFechaForm(forms.ModelForm):
    class Meta:
        model = solicitudCitaDetalle
        fields = ["fecha_hora"]


    def __init__(self, *args, **kwargs):
        super(solicitudCitaDetalleFechaForm, self).__init__(*args, **kwargs)


class solicitudLaboratorioForm(forms.ModelForm):
    class Meta: 
        model = solicitudLaboratorio
        fields = ["id_tipoLaboratorio","descripcion"]
        

class enfermedadForm(forms.ModelForm):
    class Meta:
        model = clienteEnfermedad
        fields = ["id_enfermedad", "descripcion", "estado"]

fundacion/views.py
import datetime
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, CreateView, UpdateView, ListView
from django.contrib import messages
from usuarios.models import empleado
from django.urls import reverse
from fundacion.mixins import consultaMedicaMixin, facturaMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import  enfermedadForm, solicitudCitaDetalleFechaForm, solicitudLaboratorioForm,  tratamientoForm

from .models import *

# Create your views here.

class dashboardMedico(LoginRequiredMixin, TemplateView):
    template_name = "pages/medico/dashboard_medico.html"
    def get(self, request, *args, **kwargs):
        _solicitudes = solicitudCitaDetalle.objects.filter(id_especialidad__id_area__id_area=1, aceptada=True)
        context = {
            "citas": _solicitudes
        }
        return render(request, self.template_name, context)

class dashboardRecepcion(LoginRequiredMixin, TemplateView):
    template_name = "pages/recepcion/dashboard.html"
    def get(self, request, *args, **kwargs):
        _solicitudes = solicitudCita.objects.filter(solicitud_finalizada=True)
        context = {
            "citas": _solicitudes,
            "form": solicitudCitaDetalleFechaForm()
        }
        return render(request, self.template_name, context)

class dashboardFarmacia(LoginRequiredMixin, TemplateView):
    template_name="pages/dashboard-farmacia.html"

    def get(self, request, *args, **kwargs):
        tratamientos = tratamiento.objects.filter(fecha=datetime.datetime.now())
        context = {
            "tratamientos": tratamientos
        }
        return render(request, self.template_name, context)

class dashboardLaboratorio(LoginRequiredMixin, TemplateView):
    template_name = "pages/dashboard-laboratorio.html"
    
    def get(self, request, *args, **kwargs):
        solicitudes = solicitudLaboratorio.objects.filter(aceptado=None)
        date = datetime.datetime.now()
        _laboratorio = laboratorio.objects.filter(finalizado=False)
        _laboratorioFin = laboratorio.objects.filter(finalizado=True)
        context = {
            "solicitudesLaboratorio": solicitudes,
            "laboratoriosPendientes": _laboratorio,
            "laboratorioFin": _laboratorioFin
        }
        return render(request, self.template_name, context)

class examenLaboratorioCreateView(LoginRequiredMixin, CreateView):
    template_name = "pages/dashboard-laboratorio.html"
    model = laboratorio
    fields = ["tipo_muestra","resultado", "descripcion_resultado"]
    success_url = ""
    
    def get_success_url(self):
        return reverse("fundacion:dashboard-laboratorio")
    
    def get_context_data(self, **kwargs):
        context = super(examenLaboratorioCreateView, self).get_context_data(**kwargs)
        context["titulo"] = "Examen de laboratorio"
        context["detalle"] = solicitudLaboratorio.objects.get(id_solicitudLaboratorio=self.kwargs['id_solicitudLaboratorio'])
        return context
        
    
    def form_valid(self, form):
        _solicitudLaboratorio = solicitudLaboratorio.objects.get(id_solicitudLaboratorio=self.kwargs["id_solicitudLaboratorio"])
        _solicitudLaboratorio.aceptado=True
        _solicitudLaboratorio.save()
        form.instance.id_solicitudLaboratorio = _solicitudLaboratorio
        form.instance.id_ficha = ficha.get_ficha(_solicitudCitaDetalle=_solicitudLaboratorio)
        form.save()
        facturaDetalleLaboratorio.save_factura_detalleLaboratorio(form.instance)
        messages.info(self.request, "Examen de laboratorio guardado!")
        return super().form_valid(form)

class enfermedadCreateView(LoginRequiredMixin, CreateView):
    template_name = "pages/medico/consulta_crear.html"
    success_url = "/fundacion/crear-consulta/"
    model = clienteEnfermedad
    fields = ["id_enfermedad", "descripcion","estado"]
    
    def get(self, request, *args, **kwargs):
        context = {}
        form = enfermedadForm()
        id_solicitud = kwargs["solicitud"]
        solicitud = solicitudCitaDetalle.objects.get(solicitudCitaDetalle=id_solicitud)
        context["form"]=form
        context["title"]="Registre la enfermedad detectada"
        context["solicitud_detalle"] = solicitud
        
        return render(request, self.template_name, context)
    
    def form_valid(self, form):
        id_solicitud = self.kwargs["solicitud"]
        solicitud = solicitudCitaDetalle.objects.get(solicitudCitaDetalle=id_solicitud)
        form.instance.id_expediente = solicitud.id_solicitudCita.id_expediente
        self.success_url = self.success_url+f"{solicitud.id_solicitudCita.id_expediente.id_expediente}/?detalle={solicitud.solicitudCitaDetalle}"
        messages.info(self.request, f"enfermedad {form.instance.id_enfermedad.nombre} registrada para el paciente {solicitud.id_solicitudCita.id_expediente.id_datosPersonales.get_nombreCompleto()}")
        return super().form_valid(form)

class editLaboratorioCreateView(LoginRequiredMixin, UpdateView):
    model = laboratorio
    template_name = "pages/dashboard-laboratorio.html"
    fields = ["resultado", "descripcion_resultado", "finalizado"]
    success_url= "/fundacion/dashboard-laboratorio/"

    def form_valid(self, form):
        if form.instance.resultado !="" or form.instance.resultado != None:
            form.finalizado=True
        messages.info(self.request, "Laboratorio actualizado correctamente")
        return super(editLaboratorioCreateView, self).form_valid(form)
    
class consultaMedicaCreateView(LoginRequiredMixin,consultaMedicaMixin, CreateView):
    model = consultaMedica
    fields = ["diagnostico"]
    template_name = "pages/medico/consulta_crear.html"
    success_url = ""


    def get_success_url(self):
        return reverse("fundacion:dashboard-medico")

    def get(self, request, *args, **kwargs):
        context = self.get_contexto()
        return render(request, self.template_name, context)
        
    def form_valid(self, form):
        id_detalle = self.request.GET.get("detalle")
        
        detalle=solicitudCitaDetalle.objects.get(solicitudCitaDetalle=id_detalle)
        _ficha = ficha.get_ficha(_solicitudCitaDetalle=detalle)
        form.instance.id_solicitudCitaDetalle=detalle
        form.instance.id_ficha = _ficha
        form.save()
        facturaDetalleEspecialidad.save_factura_detalle(form.instance)
        messages.info(self.request, "Consulta medica guardada y agregada a la factura")
        return super().form_valid(form)

class tratamientoCreateView(LoginRequiredMixin, CreateView):
    template_name = "pages/medico/consulta_crear.html"
    success_url = "/fundacion/crear-consulta/"
    fields = ["medicamento", "cantidad","descripcion"]
    model = tratamiento
    # tratamientoForm
    def get(self, request, *args, **kwargs):
        id_solicitud = kwargs["solicitud"]
        solicitud = solicitudCitaDetalle.objects.get(solicitudCitaDetalle=id_solicitud)

        form  = tratamientoForm()
        context= {
            "form":form,
            "solicitud_detalle":solicitud
        }
        
        return render(request, self.template_name, context)
    
    
    def form_valid(self, form, **kwargs):
        id_solicitud = self.kwargs["solicitud"]
        solicitud = solicitudCitaDetalle.objects.get(solicitudCitaDetalle=id_solicitud)
        form.instance.id_ficha = ficha.get_ficha(_solicitudCitaDetalle=solicitud)
        self.success_url = self.success_url+f"{solicitud.id_solicitudCita.id_expediente.id_expediente}/?detalle={solicitud.solicitudCitaDetalle}"
        messages.info(self.request, f"Se agrego el medicamento {form.instance.medicamento.nombre} con {form.instance.cantidad} unidades, se hara entrega en farmacia.")
        return super().form_valid(form)
    
class laboratorioSolicitudCreate(LoginRequiredMixin, CreateView):
    template_name = "pages/medico/consulta_crear.html"
    success_url = "/fundacion/crear-consulta/"
    fields = ["id_tipoLaboratorio","descripcion"]
    model = solicitudLaboratorio

    def get(self, request: HttpRequest, *args, **kwargs):
        form = solicitudLaboratorioForm()
        id_solicitud = kwargs["solicitud"]
        solicitud = solicitudCitaDetalle.objects.get(solicitudCitaDetalle=id_solicitud)
        context = {}
        context["form"]=form
        context["solicitud_detalle"] = solicitud
        return render(request, self.template_name,context )
    
    
    def form_valid(self, form) -> HttpResponse:
        _user = self.request.user
        id_solicitud = self.kwargs["solicitud"]
        solicitud = solicitudCitaDetalle.objects.get(solicitudCitaDetalle=id_solicitud)
        form.instance.id_empleado = empleado.objects.get(usuario=_user.id_usuario)
        form.instance.id_solicitudCita = solicitud.id_solicitudCita
        self.success_url = self.success_url+f"{solicitud.id_solicitudCita.id_expediente.id_expediente}/?detalle={solicitud.solicitudCitaDetalle}"
        messages.info(self.request, f"Se ha solicitado un laboratorio de {form.instance.id_tipoLaboratorio.nombre}, el paciente debe pasar al area de laboratorios para ser atendido.")
        return super().form_valid(form)
    
class tratamientoUpdateview(LoginRequiredMixin, UpdateView):
    model = tratamiento
    fields = ["estado", "cantidad"]
    success_url= ""

    def get_success_url(self):
        return reverse("fundacion:dashboard-farmacia")
    
    def form_valid(self, form):
        form.save()
        facturaDetalleFarmacia.set_detalleFactura(form.instance)
        messages.info(self.request, f"Confirmaste la entrega del medicamento {form.instance.medicamento.nombre} con {form.instance.cantidad} unidades")
        return super(tratamientoUpdateview, self).form_valid(form)
    
class solicitudDetalleUpdateDatetimeView(LoginRequiredMixin, UpdateView):
    template_name="pages/recepcion/dashboard.html"

fundacion/templates/includes/facturas.html
{% load contabilidad %}
<div class="card facturas">
    <div class="card-header detalle-factura">
            <span><strong>Paciente:</strong>{{factura.id_ficha.id_expediente.id_datosPersonales.get_nombreCompleto}}</span>
            <span><strong>Codigo expediente: </strong>{{factura.id_ficha.id_expediente.codigo_expediente}}</span>
            <span><strong>Edad:</strong> {{factura.id_ficha.id_expediente.id_datosPersonales.fecha_nacimiento}}</span>
            <span><strong>correo(s) de contacto: </strong>
                {% for contacto in factura.id_ficha.id_expediente.contacto_expediente.all %}
                        <span>{{contacto.correo_electronico}}</span>
                {% endfor %}
            </span>
            <span><strong>Total:</strong> {{factura|total:""}}</span>
            <span><a class="" href=""></a>
            </span>
    </div>
    <div class="card-body">
            {% if factura.factura_detalle.all %}
                <div class="card">
                    <div class="card-header"><h5>Detalle especialidad</h5></div>
                    <div class="card-body">
                        <div class="detalle-especialidades">
                            <span>Especialidad</span>
                            <span>costo</span>
                        </div>
                        {% for especialidad in factura.factura_detalle.all %}
                            <div class="detalle-especialidades">
                                <span>{{especialidad.id_solicitudCitaDetalle.id_especialidad.especialidad}}</span>
                                <span>{{especialidad.costo}}</span>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
            {% if factura.farmacia_detalle.all %}
                <div class="card">
                    <div class="card-header detalle-farmacia">
                        <h5>Detalle farmacia</h5>
                    </div>
                    <div class="card-body">
                        <div class="sections-farmacia">
                            <span>Medicamento</span>
                            <span>Cantidad</span>
                            <span>Precio</span>
                        </div>
                        {% for detalle in factura.farmacia_detalle.all %}
                            <div class="content-detalle-farmacia">
                                <span>{{detalle.id_tratamiento.medicamento.nombre}}</span>
                                <span>{{detalle.cantidad}}</span>
                                <span>{{detalle.precio_unitario}}</span>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
            {% if factura.cobro_factura.all %}
                <div class="card cobros">
                    <div class="card-header">
                        <h5>Pagos realizados</h5>
                    </div>
                    <div class="card-body">
                                <div class="sections-cobro">
                                    <span>Monto</span>
                                    <span>Fecha</span>
                                </div>
                    {% for cobros in factura.cobro_factura.all %}
                                <div class="sections-cobro">
                                    <span>{{cobros.id_transaccion.monto}}</span>
                                    <span>{{cobros.id_transaccion.fecha}}</span>
                                </div>
                    {% endfor %}
                    </div>
                </div>
            {% endif %}
    </div>
</div>

fundacion/templates/includes/lista_solicitudes.html
{% load static %}
{% block css_script %}
    <link rel="stylesheet" href="{% static 'css/includes/solicitudes.css' %}">
{% endblock css_script %}
<section class="citas">
        <nav class="citas-options">
            <span>Paciente</span>
            <span>Edad</span>
            <span>Enfermero</span>
            <span>Descripcion General</span>
            <span>Solicitado el</span>
            <span># areas pendientes</span>
            <span>Opciones</span>
        </nav>
        {% if citas %}
            {% for cita in citas %}
            
            {% comment %} {% if cita.get_solicitudesDetalle|length > 0 %} {% endcomment %}
                <section class="solicitud">
                    <article class="solicitud-general" data-id="{{cita.id_solicitudCita}}">
                        <span>{{cita.id_expediente.id_datosPersonales.get_nombreCompleto }}</span>
                        <span>{{cita.id_expediente.id_datosPersonales.fecha_nacimiento}}</span>
                        <span>{{cita.id_enfermero}}</span>
                        <span>{{cita.descripcion}}</span>
                        <span>{{cita.creado_en}}</span>
                        <span>
                            {{cita.get_solicitudesDetalle|length}}
                        </span>
                        <span class="last options">
                            {% if activar_edicion %}
                            {% else %}
                                    <a href="{% url 'asilo:crear-solicitud' cita.id_expediente.id_expediente %}">Finalizar</a>
                            {% endif %}
                            <span class="ver-especialidades" data-id="{{cita.id_solicitudCita}}"  href="">
                                <img src="{% static 'imagenes/chevron-down.svg' %}" alt=""> Ver
                            </span>

                        </span>
                    </article>
                    {% if cita.get_solicitudesDetalle|length > 0 %}
                        <article class= "card card-general {{cita.id_solicitudCita}}" style="display:none">
                            {% for detalle in cita.detalle_cita.all %}
                                <div class= "card card-especialidad" >
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item"><strong>Especialidad:</strong> {{detalle.id_especialidad}}</li>
                                        <li class="list-group-item"> <strong>Motivo: </strong> {{detalle.descripcion}}</li>
                                        
                                        {% if activar_edicion %}
                                            <li class="list-group-item">
                                                {% if detalle.aceptada == None %}
                                                    <h6>Asignar fecha</h6>
                                                    <form class="datetime" action="{% url 'fundacion:actualizar-detalle-solicitud' detalle.solicitudCitaDetalle %}" method="post">
                                                    {% csrf_token %}
                                                        <input class="" type="date" name="fecha_hora" id="fecha_hora">
                                                        <input class="" type="time" name="fecha_hora" id="fecha_hora">
                                                        <button class="asignar-fecha" type="submit"><img src="{% static 'imagenes/check.svg' %}" alt=""></button>
                                                    </form>
                                                    {% else %}
                                                    <span>Fecha:</span>
                                                    {{detalle.fecha_hora}}
                                                {% endif %}
                                            </li>
                                            {% if detalle.aceptada == None %}
                                                <li class="list-group-item">
                                                    <h6>rechazar</h6>
                                                    <form class="form-rechazar" action="{% url 'fundacion:rechazar-solicitud-detalle' detalle.solicitudCitaDetalle %}" method="post">
                                                            {% csrf_token %}
                                                            <input class="" name="motivo" placeholder="motivo " required type="text">
                                                            <button type="submit" class="asignar-fecha"><img src="{% static 'imagenes/check.svg' %}" alt=""></button>
                                                        </form>
                                                </li>
                                            {% endif %}
                                            <li class="list-group-item">
                                                {% if detalle.aceptada %}
                                                    <span class="text-success">
                                                        Aceptado
                                                    </span>
                                                    {% elif detalle.aceptada == False %}
                                                        <span class="text-warning">Rechazada</span>
                                                    {% else %}
                                                    <span class="text-warning">Pendiente</span>
                                                {% endif %}
                                            </li>
                                            {% if detalle.aceptada == False %}
                                                <li class="list-group-item">
                                                        <h6>motivo rechazo:</h6>
                                                        {% for motivo in detalle.motivo_rechazo_detalleSolicitud.all %}
                                                            {{motivo.motivo}}
                                                        {% endfor %}
                                                <li>
                                            {% endif %}
                                            
                                        {% endif %}
                                    </ul>
                                </div>
                            {% endfor %}
                        </article>
                    {% endif %}
                </section>
            {% comment %} {% endif %} {% endcomment %}
            {% endfor %}
        {% endif %}
        
        {% if solicitudes %}
            
        {% endif %}
            
    </section>
    {% block script_js_extra %}
        <script type='text/javascript' src="{% static 'js/fundacion/includes/lista_solicitudes.js' %}"></script>
    {% endblock script_js_extra %}