asilo/urls.py
from django.urls import path

from asilo.api import BackupsDB, ver_detalle_solicitud
from .views import *

app_name= "asilo"
urlpatterns = [
    path("",view=HomeTemplateView.as_view(), name="home"),
    path("recepcion/", view=dashboardRecepcionView.as_view(), name="dashboard-recepcion"),
    path('datos-personales/',view=datosPersonalesCreateView.as_view(), name="datos-personales"),
    path('contacto/<int:pk>/', view=contactoCreateView.as_view(), name="contacto"),
    path('expediente/<int:pk>/', view=expedienteDetailView.as_view(), name="expediente"),
    path("dashboard-medico/", view=medicoGeneralView.as_view(), name="dashboard-medico"),
    path("crear-solicitud/<int:id_expediente>/", view=solicitudCreateView.as_view(), name="crear-solicitud"),
    path("detalle-solicitud/<int:id_solicitud>/",  view=solicitudCitaDetalleCreateView.as_view(), name="detalle-solicitud"),
    path("eliminar-detalle-solicitud/<int:pk>/", view=solicitudDeleteView.as_view(), name="eliminar-detalle-solicitud"),
    path("lista-solicitudes/", view=solicitudesListaView.as_view(), name="lista-solicitudes"),
    path("editar-solicitud/<int:pk>/", view=solicitudCitaDetalleUpdateView.as_view(), name="editar-solicitud"),
    path("crear-backup/", view=BackupsDB.as_view(), name="crear-backup"),
    path("configuraciones/", view=configuracionesView.as_view(), name="configuraciones"),
    path("descargar/<str:nombre>/", view=configuracionesView.descargar_bak, name="descargar"),
    path("eliminar-backup/<str:nombre>/", view=BackupsDB.eliminar_backup, name="eliminar-backup"),
    path("ver-detalle-solicitud/<int:solicitud>/", view=ver_detalle_solicitud.as_view(), name="ver-detalle-solicitud"),
]

settings/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fundacion/', include('fundacion.urls', namespace='fundacion')),
    path('', include('asilo.urls', namespace='asilo')),
    path('usuarios/', include('usuarios.urls', namespace="usuarios")),
    path('contabilidad/',include('contabilidad.urls', namespace="contabilidad")),
    path('reportes/', include('reportes.urls', namespace="reportes")),
    path('api-auth/', include('rest_framework.urls'))
] 
urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

asilo/models.py
import uuid
from django.db import models
from django.template.defaultfilters import slugify




# Create your models here.


class expediente(models.Model):
    id_expediente = models.BigAutoField(primary_key=True)
    id_datosPersonales = models.ForeignKey("usuarios.datosPersonales", unique=True, related_name="expediente_datosPersonales", on_delete=models.CASCADE)
    codigo_expediente = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return f"{self.id_datosPersonales.primer_nombre}"

    def save(self, *args, **kwargs):
        super(expediente, self).save(*args, **kwargs)
        if self.codigo_expediente is None:
            self.codigo_expediente = slugify(f"SP-{self.id_expediente}")
            self.save()

    def get_expediente(datosPersonales):
        exp = expediente()
        exp.id_datosPersonales = datosPersonales
        exp.save()
        return exp

class contacto(models.Model):
    id_contacto = models.BigAutoField(primary_key=True)
    id_expediente = models.ForeignKey("asilo.expediente", related_name="contacto_expediente", verbose_name=("expediente"), on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50, null=False, blank=False)
    numero_telefono = models.CharField(max_length=8)
    correo_electronico = models.EmailField(max_length=254, blank=True, null=True)
    parentesco = models.CharField(max_length=50, null=False, blank=True)
    estado = models.BooleanField(default=True)
    def __str__(self):
        return f"{self.parentesco} {self.id_expediente.id_datosPersonales.primer_nombre} {self.correo_electronico}"

class cuenta(models.Model):
    id_cuenta = models.BigAutoField(primary_key=True)
    id_expediente = models.ForeignKey("asilo.expediente", verbose_name=("Expediente"), on_delete=models.CASCADE)
    deuda = models.BooleanField(default=0 )
    creado_en = models.DateTimeField(auto_now=True)

asilo/forms.py
from django import forms
from asilo.models import contacto
from fundacion.models import solicitudCita, solicitudCitaDetalle


class contactoForm(forms.ModelForm):
    
    class Meta:
        model = contacto
        excludes = ["id_expediente"]
        
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["fecha_nacimiento"].widget = forms.widgets.DateTimeInput()

asilo/views.py
from urllib import request
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from asilo.api import BackupsDB
from asilo.herramientas import backups
from asilo.mixins import asiloMixin, medicoMixin
from django.urls import reverse
from asilo.models import expediente, contacto
from fundacion.forms import solicitudCitaDetalleForm, solicitudCitaForm
from fundacion.mixins import recepcionMixin
from fundacion.models import solicitudCita, solicitudCitaDetalle
from reportes.correoElectronico import correo
from usuarios.forms import datosPersonalesForm
from django.contrib.auth.mixins import LoginRequiredMixin
from usuarios.models import datosPersonales, empleado
from django.contrib import messages
from django.views.generic import TemplateView, CreateView,ListView,  DetailView, DeleteView, UpdateView

# Create your views here.

class HomeTemplateView(LoginRequiredMixin,asiloMixin, TemplateView):
    template_name = "asilo/home.html"
    
    def get(self, request, *args, **kwargs):
        context = {}
        context =self.get_context_for_home()
        return render(request, self.template_name, context)

class dashboardRecepcionView(LoginRequiredMixin,recepcionMixin, TemplateView):
    template_name = "asilo/recepcion/dashboard.html"

    def get(self, request, *args, **kwargs):
        contexto = self.get_contexto()
        return render(request, self.template_name, contexto)
        
class datosPersonalesCreateView(LoginRequiredMixin, CreateView):
    model = datosPersonales
    template_name  = "asilo/includes/forms.html"
    fields = "__all__"
    success_url = ""
    form = datosPersonalesForm()

    def get_context_data(self, **kwargs):
        context = super(datosPersonalesCreateView, self).get_context_data(**kwargs)
        context['titulo'] = "Creando expediente del Cliente"
        context['subtitulo']= "Agregue los datos personales"
        return context
        

    def form_valid(self, form):
        form.save()
        _expediente= expediente.get_expediente(form.instance)
        self.success_url= reverse('asilo:contacto', kwargs={'pk':_expediente.id_expediente})
        return super().form_valid(form)

class contactoCreateView(LoginRequiredMixin, CreateView):
    model = contacto
    template_name = "asilo/includes/forms.html"
    fields = ["nombre", "numero_telefono", "correo_electronico", "parentesco"]
    success_url = ""
    
    def get_context_data(self, **kwargs):
        context = super(contactoCreateView, self).get_context_data(**kwargs)
        context['titulo'] = "Agregar datos de contacto"
        return context

    def form_valid(self, form):
        form.instance.id_expediente=expediente.objects.get(id_expediente=self.kwargs['pk'])
        form.save()
        self.success_url = reverse("asilo:expediente", kwargs={'pk':self.kwargs['pk']})
        messages.sucess(self.request, "Expediente creado con exito!")
        return super().form_valid(form)

class expedienteDetailView(LoginRequiredMixin, DetailView):
    model = expediente
    template_name = "asilo/recepcion/expediente_detalle.html"
    
    def get(self, request, *args, **kwargs):
        context = {}
        _expediente = expediente.objects.get(id_expediente=kwargs['pk'])
        context['expediente'] = _expediente
        context['contacto'] = contacto.objects.filter(id_expediente=_expediente.id_expediente)
        return render(request, self.template_name, context)

class medicoGeneralView(LoginRequiredMixin, TemplateView):
    template_name = "asilo/medico/dashboard.html"
    
    
    def get(self, request):
        context = {}
        print(f"correo {settings.EMAIL_HOST_USER} with pass: {settings.EMAIL_HOST_PASSWORD}")
        _solicitudes = solicitudCita.objects.all().order_by("creado_en")[:15]
        context["solicitudes"] = _solicitudes
        
        return render(request, self.template_name, context)

class solicitudCreateView(LoginRequiredMixin, CreateView):
    template_name = "asilo/medico/crear_solicitud.html"
    model = solicitudCita
    fields = ["id_enfermero", "descripcion"]
    success_url = "/detalle-solicitud/"

    def get(self, request, *args, **kwargs):
        id_expediente = kwargs["id_expediente"]
        
        form = solicitudCitaForm()
        context = {"form":form}
        context['title']="Agregue los datos generales de la solicitud"
        context['expediente'] = expediente.objects.get(id_expediente=id_expediente)
        solicitud_pendiente, id_solicitud = solicitudCita.get_solicitud(id_expediente=id_expediente)
        if solicitud_pendiente:
            return HttpResponseRedirect(reverse('asilo:detalle-solicitud', kwargs={'id_solicitud':id_solicitud}))
        return render(request, self.template_name, context)

    def form_valid(self, form):
        id_expediente =self.kwargs["id_expediente"]
        _expediente = expediente.objects.get(id_expediente=id_expediente)
        form.instance.id_expediente = _expediente
        form.save()
        self.success_url = self.success_url+ f"{form.instance.id_solicitudCita}/"
        return super().form_valid(form)

class solicitudCitaDetalleCreateView(LoginRequiredMixin,medicoMixin, CreateView):
    template_name = "asilo/medico/crear_solicitud.html"
    model = solicitudCitaDetalle
    fields = ["id_especialidad","descripcion"]
    success_url = "/detalle-solicitud/"
    
    def get(self, request, *args, **kwargs):

        id_solicitud = kwargs["id_solicitud"]
        _solicitud = solicitudCita.objects.get(id_solicitudCita=id_solicitud)
        context = {}
        data = {"id_solicitudCita":_solicitud}
        form = solicitudCitaDetalleForm(initial=data)
        context = {
            "solicitud": _solicitud,
            "form":form,
            "pagina": "detalle"
        }
        context['title']="Especialidades disponibles"
        detalles = solicitudCitaDetalle.objects.filter(id_solicitudCita=_solicitud)
        if len(detalles) > 0:
            context["detalles"] = detalles
        return render(request, self.template_name, context)

    def form_valid(self, form):
        id_solicitud = self.kwargs["id_solicitud"]
        _solicitud = solicitudCita.objects.get(id_solicitudCita=id_solicitud)
        form.instance.id_solicitudCita = _solicitud
        form.save()
        if self.request.POST["proximo_paso"]:
            proximo_paso = self.request.POST["proximo_paso"]
            if proximo_paso =="guardar_y_repetir":
                return HttpResponseRedirect(reverse('asilo:detalle-solicitud', kwargs={'id_solicitud':self.kwargs['id_solicitud']}))
            if proximo_paso =="guardar_y_enviar":
                _solicitudCita= solicitudCita.objects.get(id_solicitudCita=form.instance.id_solicitudCita.id_solicitudCita)
                _solicitudCita.solicitud_finalizada=True
                _solicitudCita.save()
                self.enviar_correo(_solicitudCita)
                messages.success(self.request, f"Se ha creado una nueva solicitud para el paciente, {_solicitud.id_expediente.id_datosPersonales.get_nombreCompleto()}")
                return HttpResponseRedirect('/dashboard-medico/')
        else:
            return HttpResponseRedirect(reverse('asilo:detalle-solicitud', kwargs={'id_solicitud':self.kwargs['id_solicitud']}))

class solicitudCitaDetalleUpdateView(LoginRequiredMixin,medicoMixin, UpdateView):
    template_name = "asilo/medico/crear_solicitud.html"
    model = solicitudCitaDetalle
    fields = ["id_especialidad","descripcion"]
    success_url = "/detalle-solicitud/"

    def form_valid(self, form):
        form.save()
        # self.success_url = self.success_url+ f"{form.instance.id_solicitudCita}/"
        return HttpResponseRedirect(reverse('asilo:detalle-solicitud', kwargs={'id_solicitud':form.instance.id_solicitudCita.id_solicitudCita}))
        
class solicitudDeleteView(LoginRequiredMixin, DeleteView):
    model = solicitudCitaDetalle
    success_url = success_url = "/detalle-solicitud/"
    template_name = "medico/crear_solicitud.html"
    
    def form_valid(self, form):
        # page navegara a finalizar la solicitud
        self.success_url= self.success_url+f"{self.object.id_solicitudCita.id_solicitudCita}/"
        messages.success(self.request, "la solicitud se ha eliminado  correctamente")
        return super().form_valid(form)

class solicitudesListaView(LoginRequiredMixin, ListView):
    template_name = "asilo/medico/solicitudes.html"
    model = solicitudCita

    def get_context_data(self, **kwargs):
        context = super(solicitudesListaView, self).get_context_data(**kwargs)
        context["citas"] = solicitudCita.objects.filter(solicitud_finalizada=False)
        context["historial_citas"] = solicitudCita.objects.all().order_by("creado_en")
        return context
    
class configuracionesView(LoginRequiredMixin, TemplateView):
    template_name = "asilo/configuraciones.html"

    def get(self, request, *args, **kwargs):
        context = {}
        backup = backups()
        archivos = backup.get_backupsExistentes()
        context['backups']=archivos
        return render(request, self.template_name, context)
    
    
    def descargar_bak(request, nombre):
        backup = backups()
        file = backup.get_bak(nombre)
        response = HttpResponse(file, content_type='multipart/alternative')
        response['Content-Disposition'] = f'attachment; filename={nombre}'
        return response
    
class empleadoCreateView(LoginRequiredMixin, CreateView):
    model = empleado
    

asilo/templates/asilo/NuevaSolicitudMedica.html
<div>
<fieldset>
<legend>Nueva cita medica</legend>
<h4>Paciente: {{solicitudes.id_expediente.id_datosPersonales.get_nombreCompleto}}</h4>
    {% for solicitud in solicitudes.detalle_cita.all %}
        <ul>
            <li><strong>Especialidad: </strong> {{solicitud.id_especialidad.especialidad}}</li>
            <li><strong>Descripcion: </strong>{{solicitud.descripcion}}</li>
            <li> <strong>Area: </strong> {{solicitud.id_especialidad.id_area.nombre}}</li>
            <li><strong>Precio del Servicio</strong> {{solicitud.id_especialidad.costo}}</li>
        </ul>
    {% endfor %}
    <small>Creada en: {{solicitudes.creado_en}}</small>
    <small>- Pendiente de confirmar en la clinica medica -</small>
</fieldset>
   
    
</div>

asilo/templates/asilo/base_asilo.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    
    {% block css_script %}{% endblock css_script %}
    {% block css_script_extra %}{% endblock css_script_extra %}
    <title>
        {% block tile_page %}Asilo{% endblock tile_page %}
    </title>
    <link rel="stylesheet" href="{% static 'css/preconstrucciones.css' %}">
    <link rel="stylesheet" href="{% static 'css/recepcion/base.css' %}">
</head>
<body>
    <div class="base">
        {% block nav %}
            {% include 'asilo/includes/nav.html' %}
        {% endblock nav %}
        <section class="dashboard-sections">
            <aside class="dashboard-aside">
                {% block asideHeader %}
                    <a class="clientes " href="{% url 'asilo:dashboard-recepcion' %}?pagina=clientes"><img class="ico" src="{% static 'imagenes/people.svg' %}" alt="">  clientes</a>
                    <a class="solicitudes" href="{% url 'asilo:lista-solicitudes' %}"><img class="ico" src="{% static 'imagenes/paste.svg' %}" alt="">solicitudes</a>
                    <a class="configuraciones" href="{% url 'asilo:configuraciones' %}"><img class="ico" src="{% static 'imagenes/gear.svg' %}" alt="">Configuraciones</a>
                {% endblock asideHeader %}
                
                {% block aside %}
                
                {% endblock aside %}
            </aside>
            <article class="dashboard-body">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% block section %}
                    
                {% endblock section %}
            </article>
        
        </section>
    </div>
    {% comment %} modal para mostrar contenido flotante {% endcomment %}
    <div id="myModal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Especialidades solicitadas</h5>
                
            </div>
            <div class="modal-body">
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
            </div>
        </div>
    </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-- JavaScript Bundle with Popper -->
{% comment %} <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> {% endcomment %}
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/asilo/base.js' %}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>


<script type="text/javascript">
        $(document).ready(()=> {
        $(".table").DataTable({
                "language": {"url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"}
            })
        })
        {% block script_js %}
            
        {% endblock script_js %}
        
</script>

{% block script_js_extra %}{% endblock script_js_extra %}
</html>

asilo/templates/asilo/clientes.html
{% load static %}
{% load recepcion %}
    <article class="expedientes">
            <h4>Clientes</h4>
            <a class="btn btn-outline-success" href="{% url 'asilo:datos-personales' %}">
                <img src="{% static 'imagenes/person-add.svg' %}" alt=""> 
                    Agregar un cliente
            </a>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Expediente</th>
                        <th>Nombre</th>
                        <th>Edad</th>
                        <th>DNI</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cliente in clientes %}
                        <tr>
                            <td>SP-{{cliente.id_expediente}}</td>
                            <td>{{cliente.id_datosPersonales.get_nombreCompleto}}</td>
                            <td>{{cliente.id_datosPersonales.fecha_nacimiento}}</td>
                            <td>{{cliente.id_datosPersonales.dni}}</td>
                            <td>
                                <a href="{% url 'asilo:expediente' cliente.id_expediente %}" title="Expediente clinico del cliente" ><img src="{% static 'imagenes/repo.svg' %}" alt=""></a>
                                {% comment %} {% if request.user.pk|especialidad:request.user.pk == "recepcionista" or request.user.pk|especialidad:request.user.pk == "medico" %} {% endcomment %}
                                    <a href="{% url 'asilo:crear-solicitud' cliente.id_expediente %}" title="Crear Consulta Medica" ><img src="{% static 'imagenes/link-external.svg' %}" alt=""></a>
                                {% comment %} {% endif %} {% endcomment %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </article>

asilo/templates/asilo/configuraciones.html
{% extends 'asilo/base_asilo.html' %}
{% load static %}
{% load recepcion %}

{% block css_script %}
    <link rel="stylesheet" href="{% static 'css/includes/configuraciones.css' %}">
{% endblock css_script %}
{% block section %}
    <div class="canva">
        <nav class="nav-top">
            <span class="seleccionado-top">backups de base de datos</span>
            <span>usuarios con acceso</span>
        </nav>
        <span class="btn btn-outline-success crear-backup">Crear backup</span>
        <article class="backups header">
            <div class="backups-list">
                <span>Nombre</span>
                <span>Fecha de creacion</span>
                <span>Opciones</span>
            </div>
            {% for backup in backups %}
            <div class="backups-body">
                <span>{{backup.nombre}}</span>
                <span>{{backup.fecha}}</span>
                <span>
                    <a class="btn btn-outline-info" href="{% url 'asilo:descargar' backup.nombre %}">Descargar</a>
                    <a class="eliminar" data-name="{{backup.nombre}}" href="http://"><img src="{% static 'imagenes/trash.svg' %}" alt=""></a>
                </span>
            </div>
            {% endfor %}
        </article>
    </div>
{% endblock %}
{% block script_js_extra %}
    <script src="{% static 'js/asilo/configuraciones.js' %}"></script>
{% endblock script_js_extra %}

asilo/templates/asilo/home.html
{% extends 'asilo/base_asilo.html' %}
{% load static %}
{% block css_script %}
   <link rel="stylesheet" href="{% static 'css/home.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://cdn.amcharts.com/lib/5/index.js"></script>
        <script src="https://cdn.amcharts.com/lib/5/xy.js"></script>
        <script src="https://cdn.amcharts.com/lib/5/percent.js"></script>
        <script src="https://cdn.amcharts.com/lib/5/themes/Animated.js"></script>
        <script src="{% static 'js/asilo/home.js' %}"></script>
{% endblock css_script %}
{% block section %}
    <section class="body-home">
        <article class="card card-home">
            <h5>Asilo</h5>
        </article>
        <div class="graficas">
            <article class="card">
            <div class="card-header">
                Enfermedades mas comunes
            </div>
            <div class="card-body">
                <div id="chartdiv"></div>
            </div>
            
        </article>
        <article class="card">
            <div class="card-header">
                flujo de caja
            </div>
            <div class="card-body">
                <div id="chartCaja"></div>
            </div>
            
        </article>
        </div>
        
    </section>
    <input type="hidden" id="chartCajaData" value="{{flujo_caja}}" name="">
    <input type="hidden" id="chartEnfermedadData" name="" value="{{enfermedades}}">
{% endblock section %}

{% block script_js_extra %}

{% endblock script_js_extra %}