asilo/urls.py
from django.urls import path

from asilo.api import BackupsDB, ver_detalle_solicitud
from .views import *

app_name= "asilo"
urlpatterns = [
    path("",view=HomeTemplateView.as_view(), name="home"),
    path("recepcion/", view=dashboardRecepcionView.as_view(), name="dashboard-recepcion"),
    path('datos-personales/',view=datosPersonalesCreateView.as_view(), name="datos-personales"),
    path('contacto/<int:pk>/', view=contactoCreateView.as_view(), name="contacto"),
    path('expediente/<int:pk>/', view=expedienteDetailView.as_view(), name="expediente"),
    path("dashboard-medico/", view=medicoGeneralView.as_view(), name="dashboard-medico"),
    path("crear-solicitud/<int:id_expediente>/", view=solicitudCreateView.as_view(), name="crear-solicitud"),
    path("detalle-solicitud/<int:id_solicitud>/",  view=solicitudCitaDetalleCreateView.as_view(), name="detalle-solicitud"),
    path("eliminar-detalle-solicitud/<int:pk>/", view=solicitudDeleteView.as_view(), name="eliminar-detalle-solicitud"),
    path("lista-solicitudes/", view=solicitudesListaView.as_view(), name="lista-solicitudes"),
    path("editar-solicitud/<int:pk>/", view=solicitudCitaDetalleUpdateView.as_view(), name="editar-solicitud"),
    path("crear-backup/", view=BackupsDB.as_view(), name="crear-backup"),
    path("configuraciones/", view=configuracionesView.as_view(), name="configuraciones"),
    path("descargar/<str:nombre>/", view=configuracionesView.descargar_bak, name="descargar"),
    path("eliminar-backup/<str:nombre>/", view=BackupsDB.eliminar_backup, name="eliminar-backup"),
    path("ver-detalle-solicitud/<int:solicitud>/", view=ver_detalle_solicitud.as_view(), name="ver-detalle-solicitud"),
]

fundacion/urls.py
from django.urls import path
from fundacion.views import *


app_name = 'fundacion'


urlpatterns = [
    path('dashboard-medico/', view=dashboardMedico.as_view(), name='dashboard-medico'),
    path('crear-consulta/<int:id_expediente>/', view=consultaMedicaCreateView.as_view(), name='crear-consulta'),
    path("crear-tratamiento/<int:solicitud>/",view=tratamientoCreateView.as_view(), name="crear-tratamiento"),
    path("solicitar-laboratorio/<int:solicitud>/",view=laboratorioSolicitudCreate.as_view(), name="solicitar-laboratorio"),
    path("", view=dashboardRecepcion.as_view(), name="dashboard-recepcion"),
    path("crear-laboratorio/<int:id_solicitudLaboratorio>/", view=examenLaboratorioCreateView.as_view(), name="crear-laboratorio"),
    path("actualizar-laboratorio/<int:pk>/", view=editLaboratorioCreateView.as_view(), name="editar-laboratorio"),
    path("actualizar-detalle-solicitud/<int:pk>/", view=solicitudDetalleUpdateDatetimeView.as_view(), name="actualizar-detalle-solicitud"),
    path("rechazar-solicitud-detalle/<int:pk>/", view=rechazarDetalleRechazarView.as_view(), name='rechazar-solicitud-detalle'),
    path("dashboard-laboratorio/", view=dashboardLaboratorio.as_view(), name="dashboard-laboratorio"),
    path("dashboard-farmacia/", view=dashboardFarmacia.as_view(), name="dashboard-farmacia"),
    path("actualizar-tratamiento/<int:pk>/", view=tratamientoUpdateview.as_view(), name="actualizar-tratamiento"),
    path("fichas/", view=fichasListView.as_view(), name="fichas"),
    path("crear-factura/<int:id_ficha>/", view=facturaCrear.as_view(), name="crear-factura"),
    path("facturas/", view=facturasListView.as_view(), name="facturas"),
    path("enfermedad/<int:solicitud>/", view=enfermedadCreateView.as_view(), name="enfermedad")
]   

# <int:id_cliente>/

settings/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fundacion/', include('fundacion.urls', namespace='fundacion')),
    path('', include('asilo.urls', namespace='asilo')),
    path('usuarios/', include('usuarios.urls', namespace="usuarios")),
    path('contabilidad/',include('contabilidad.urls', namespace="contabilidad")),
    path('reportes/', include('reportes.urls', namespace="reportes")),
    path('api-auth/', include('rest_framework.urls'))
] 
urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usuarios/urls.py
from django.contrib.auth.views import LogoutView

from django.urls import path

from usuarios.views import AdminLogin, expedienteSearch

app_name= "usuarios"
urlpatterns = [
    path("buscar-expediente/", view=expedienteSearch.as_view(), name="buscar-expediente"),
    path("iniciar-sesion/",view=AdminLogin.as_view(), name="iniciar-sesion"),
    path("logout/", LogoutView.as_view(), name="logout")
]

fundacion/forms.py
from django import forms

from usuarios.models import empleado
from .models import clienteEnfermedad, consultaMedica, enfermedad,  solicitudCita, solicitudCitaDetalle, solicitudLaboratorio, tratamiento


class consultaMedicaForm( forms.ModelForm):
    class Meta:
        model = consultaMedica
        fields = ["diagnostico"]
        
        
class tratamientoForm( forms.ModelForm):
    class Meta:
        model = tratamiento
        fields = ["medicamento","cantidad", "descripcion"]
    def __init__(self, *args, **kwargs):
        super(tratamientoForm, self).__init__(*args, **kwargs)
        

class solicitudCitaForm(forms.ModelForm):
    pagina = forms.CharField(max_length=10, required=True, widget=forms.HiddenInput())
    class Meta:
        model = solicitudCita
        fields = ["id_enfermero","descripcion"]
        

    def __init__(self, *args, **kwargs):
        super(solicitudCitaForm, self).__init__(*args, **kwargs)
        choices = [(empleado.id_empleado, empleado.id_datos_personales.get_nombreCompleto()) for empleado in  empleado.objects.filter(id_empleado_especialidad__nombre__icontains="Enfermeria")]
        self.fields["id_enfermero"].choices = choices
        self.fields["pagina"].initial = "solicitud"


class solicitudCitaDetalleForm(forms.ModelForm):
    pagina = forms.CharField(max_length=50, required=True, widget=forms.HiddenInput())
    class Meta:
        model = solicitudCitaDetalle
        fields = ["id_especialidad", "descripcion"]


    def __init__(self, *args, **kwargs):
        super(solicitudCitaDetalleForm, self).__init__(*args, **kwargs)
        self.fields["pagina"].initial ="detalle"


class solicitudCitaDetalleFechaForm(forms.ModelForm):
    class Meta:
        model = solicitudCitaDetalle
        fields = ["fecha_hora"]


    def __init__(self, *args, **kwargs):
        super(solicitudCitaDetalleFechaForm, self).__init__(*args, **kwargs)


class solicitudLaboratorioForm(forms.ModelForm):
    class Meta: 
        model = solicitudLaboratorio
        fields = ["id_tipoLaboratorio","descripcion"]
        

class enfermedadForm(forms.ModelForm):
    class Meta:
        model = clienteEnfermedad
        fields = ["id_enfermedad", "descripcion", "estado"]

fundacion/views.py
import datetime
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, CreateView, UpdateView, ListView
from django.contrib import messages
from usuarios.models import empleado
from django.urls import reverse
from fundacion.mixins import consultaMedicaMixin, facturaMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import  enfermedadForm, solicitudCitaDetalleFechaForm, solicitudLaboratorioForm,  tratamientoForm

from .models import *

# Create your views here.

class dashboardMedico(LoginRequiredMixin, TemplateView):
    template_name = "pages/medico/dashboard_medico.html"
    def get(self, request, *args, **kwargs):
        _solicitudes = solicitudCitaDetalle.objects.filter(id_especialidad__id_area__id_area=1, aceptada=True)
        context = {
            "citas": _solicitudes
        }
        return render(request, self.template_name, context)

class dashboardRecepcion(LoginRequiredMixin, TemplateView):
    template_name = "pages/recepcion/dashboard.html"
    def get(self, request, *args, **kwargs):
        _solicitudes = solicitudCita.objects.filter(solicitud_finalizada=True)
        context = {
            "citas": _solicitudes,
            "form": solicitudCitaDetalleFechaForm()
        }
        return render(request, self.template_name, context)

class dashboardFarmacia(LoginRequiredMixin, TemplateView):
    template_name="pages/dashboard-farmacia.html"

    def get(self, request, *args, **kwargs):
        tratamientos = tratamiento.objects.filter(fecha=datetime.datetime.now())
        context = {
            "tratamientos": tratamientos
        }
        return render(request, self.template_name, context)

class dashboardLaboratorio(LoginRequiredMixin, TemplateView):
    template_name = "pages/dashboard-laboratorio.html"
    
    def get(self, request, *args, **kwargs):
        solicitudes = solicitudLaboratorio.objects.filter(aceptado=None)
        date = datetime.datetime.now()
        _laboratorio = laboratorio.objects.filter(finalizado=False)
        _laboratorioFin = laboratorio.objects.filter(finalizado=True)
        context = {
            "solicitudesLaboratorio": solicitudes,
            "laboratoriosPendientes": _laboratorio,
            "laboratorioFin": _laboratorioFin
        }
        return render(request, self.template_name, context)

class examenLaboratorioCreateView(LoginRequiredMixin, CreateView):
    template_name = "pages/dashboard-laboratorio.html"
    model = laboratorio
    fields = ["tipo_muestra","resultado", "descripcion_resultado"]
    success_url = ""
    
    def get_success_url(self):
        return reverse("fundacion:dashboard-laboratorio")
    
    def get_context_data(self, **kwargs):
        context = super(examenLaboratorioCreateView, self).get_context_data(**kwargs)
        context["titulo"] = "Examen de laboratorio"
        context["detalle"] = solicitudLaboratorio.objects.get(id_solicitudLaboratorio=self.kwargs['id_solicitudLaboratorio'])
        return context
        
    
    def form_valid(self, form):
        _solicitudLaboratorio = solicitudLaboratorio.objects.get(id_solicitudLaboratorio=self.kwargs["id_solicitudLaboratorio"])
        _solicitudLaboratorio.aceptado=True
        _solicitudLaboratorio.save()
        form.instance.id_solicitudLaboratorio = _solicitudLaboratorio
        form.instance.id_ficha = ficha.get_ficha(_solicitudCitaDetalle=_solicitudLaboratorio)
        form.save()
        facturaDetalleLaboratorio.save_factura_detalleLaboratorio(form.instance)
        messages.info(self.request, "Examen de laboratorio guardado!")
        return super().form_valid(form)

class enfermedadCreateView(LoginRequiredMixin, CreateView):
    template_name = "pages/medico/consulta_crear.html"
    success_url = "/fundacion/crear-consulta/"
    model = clienteEnfermedad
    fields = ["id_enfermedad", "descripcion","estado"]
    
    def get(self, request, *args, **kwargs):
        context = {}
        form = enfermedadForm()
        id_solicitud = kwargs["solicitud"]
        solicitud = solicitudCitaDetalle.objects.get(solicitudCitaDetalle=id_solicitud)
        context["form"]=form
        context["title"]="Registre la enfermedad detectada"
        context["solicitud_detalle"] = solicitud
        
        return render(request, self.template_name, context)
    
    def form_valid(self, form):
        id_solicitud = self.kwargs["solicitud"]
        solicitud = solicitudCitaDetalle.objects.get(solicitudCitaDetalle=id_solicitud)
        form.instance.id_expediente = solicitud.id_solicitudCita.id_expediente
        self.success_url = self.success_url+f"{solicitud.id_solicitudCita.id_expediente.id_expediente}/?detalle={solicitud.solicitudCitaDetalle}"
        messages.info(self.request, f"enfermedad {form.instance.id_enfermedad.nombre} registrada para el paciente {solicitud.id_solicitudCita.id_expediente.id_datosPersonales.get_nombreCompleto()}")
        return super().form_valid(form)

class editLaboratorioCreateView(LoginRequiredMixin, UpdateView):
    model = laboratorio
    template_name = "pages/dashboard-laboratorio.html"
    fields = ["resultado", "descripcion_resultado", "finalizado"]
    success_url= "/fundacion/dashboard-laboratorio/"

    def form_valid(self, form):
        if form.instance.resultado !="" or form.instance.resultado != None:
            form.finalizado=True
        messages.info(self.request, "Laboratorio actualizado correctamente")
        return super(editLaboratorioCreateView, self).form_valid(form)
    
class consultaMedicaCreateView(LoginRequiredMixin,consultaMedicaMixin, CreateView):
    model = consultaMedica
    fields = ["diagnostico"]
    template_name = "pages/medico/consulta_crear.html"
    success_url = ""


    def get_success_url(self):
        return reverse("fundacion:dashboard-medico")

    def get(self, request, *args, **kwargs):
        context = self.get_contexto()
        return render(request, self.template_name, context)
        
    def form_valid(self, form):
        id_detalle = self.request.GET.get("detalle")
        
        detalle=solicitudCitaDetalle.objects.get(solicitudCitaDetalle=id_detalle)
        _ficha = ficha.get_ficha(_solicitudCitaDetalle=detalle)
        form.instance.id_solicitudCitaDetalle=detalle
        form.instance.id_ficha = _ficha
        form.save()
        facturaDetalleEspecialidad.save_factura_detalle(form.instance)
        messages.info(self.request, "Consulta medica guardada y agregada a la factura")
        return super().form_valid(form)

class tratamientoCreateView(LoginRequiredMixin, CreateView):
    template_name = "pages/medico/consulta_crear.html"
    success_url = "/fundacion/crear-consulta/"
    fields = ["medicamento", "cantidad","descripcion"]
    model = tratamiento
    # tratamientoForm
    def get(self, request, *args, **kwargs):
        id_solicitud = kwargs["solicitud"]
        solicitud = solicitudCitaDetalle.objects.get(solicitudCitaDetalle=id_solicitud)

        form  = tratamientoForm()
        context= {
            "form":form,
            "solicitud_detalle":solicitud
        }
        
        return render(request, self.template_name, context)
    
    
    def form_valid(self, form, **kwargs):
        id_solicitud = self.kwargs["solicitud"]
        solicitud = solicitudCitaDetalle.objects.get(solicitudCitaDetalle=id_solicitud)
        form.instance.id_ficha = ficha.get_ficha(_solicitudCitaDetalle=solicitud)
        self.success_url = self.success_url+f"{solicitud.id_solicitudCita.id_expediente.id_expediente}/?detalle={solicitud.solicitudCitaDetalle}"
        messages.info(self.request, f"Se agrego el medicamento {form.instance.medicamento.nombre} con {form.instance.cantidad} unidades, se hara entrega en farmacia.")
        return super().form_valid(form)
    
class laboratorioSolicitudCreate(LoginRequiredMixin, CreateView):
    template_name = "pages/medico/consulta_crear.html"
    success_url = "/fundacion/crear-consulta/"
    fields = ["id_tipoLaboratorio","descripcion"]
    model = solicitudLaboratorio

    def get(self, request: HttpRequest, *args, **kwargs):
        form = solicitudLaboratorioForm()
        id_solicitud = kwargs["solicitud"]
        solicitud = solicitudCitaDetalle.objects.get(solicitudCitaDetalle=id_solicitud)
        context = {}
        context["form"]=form
        context["solicitud_detalle"] = solicitud
        return render(request, self.template_name,context )
    
    
    def form_valid(self, form) -> HttpResponse:
        _user = self.request.user
        id_solicitud = self.kwargs["solicitud"]
        solicitud = solicitudCitaDetalle.objects.get(solicitudCitaDetalle=id_solicitud)
        form.instance.id_empleado = empleado.objects.get(usuario=_user.id_usuario)
        form.instance.id_solicitudCita = solicitud.id_solicitudCita
        self.success_url = self.success_url+f"{solicitud.id_solicitudCita.id_expediente.id_expediente}/?detalle={solicitud.solicitudCitaDetalle}"
        messages.info(self.request, f"Se ha solicitado un laboratorio de {form.instance.id_tipoLaboratorio.nombre}, el paciente debe pasar al area de laboratorios para ser atendido.")
        return super().form_valid(form)
    
class tratamientoUpdateview(LoginRequiredMixin, UpdateView):
    model = tratamiento
    fields = ["estado", "cantidad"]
    success_url= ""

    def get_success_url(self):
        return reverse("fundacion:dashboard-farmacia")
    
    def form_valid(self, form):
        form.save()
        facturaDetalleFarmacia.set_detalleFactura(form.instance)
        messages.info(self.request, f"Confirmaste la entrega del medicamento {form.instance.medicamento.nombre} con {form.instance.cantidad} unidades")
        return super(tratamientoUpdateview, self).form_valid(form)
    
class solicitudDetalleUpdateDatetimeView(LoginRequiredMixin, UpdateView):
    template_name="pages/recepcion/dashboard.html"

fundacion/templates/pages/base_fundacion.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/preconstrucciones.css' %}">
    <link rel="stylesheet" href="{% static 'css/fundacion/base_fundacion.css' %}">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    {% block script_css %}
    
    {% endblock script_css %}
    <title>Senes</title>
</head>
<body>
    <header class="header-base">
        <nav class="nav-options-medico">
             <a class="logo" href="{% url 'asilo:home' %}">
                    <img src="{% static 'imagenes/gh_icon.svg' %}" alt="">
                    <span>senes proteges</span>
                </a>
            <div class="dropdown dropdown-perfil">
                <button class=" toggle-perfil" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src="{% static 'imagenes/person.svg' %}" alt="">
                </button>
                <div class="menu-perfil" style="display:none">
                    <a class="dropdown-item" href="{% url 'usuarios:logout' %}">Cerrar sesion</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="body-recepcion">
        <aside class="aside-recepcion">
            <a class="clinica"  href="{% url 'fundacion:dashboard-medico' %}"><img class="ico" src="{% static 'imagenes/hospital.svg' %}" alt=""> Clinica Medica</a>
            <a class="recepcion" href="{% url 'fundacion:dashboard-recepcion' %}"><img src="{% static 'imagenes/history.svg' %}" alt=""> Recepcion</a>
            <a class="laboratorio" href="{% url 'fundacion:dashboard-laboratorio' %}"><img src="{% static 'imagenes/beaker.svg' %}" alt=""> Laboratorio</a>
            <a class="farmacia" href="{% url 'fundacion:dashboard-farmacia' %}"><img class="ico" src="{% static 'imagenes/medicina.svg' %}" alt=""> Farmacia</a>
            <a class="facturas" href="{% url 'fundacion:facturas' %}"><img class="ico" src="{% static 'imagenes/facturas.svg' %}" alt="">  Facturas</a>
        </aside>
        <section class="principal">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            {% block body %}
                    
            {% endblock body %}
    </section>
    </div>
</body>
<script src="{% static 'js/fundacion/base_fundacion.js' %}"></script>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript">
        $(document).ready(()=> {
        $(".table").DataTable({
                "language": {"url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"}
            })
        })
        {% block js_code %}{% endblock js_code %}
</script>
{% block script_js %}
            
{% endblock script_js %}
{% block script_js_extra %}{% endblock script_js_extra %}
</html>

fundacion/templates/pages/dashboard-facturas.html
{% extends 'pages/base_fundacion.html' %}
{% load static %}
{% load contabilidad %}
{% block script_css %}
    <link rel="stylesheet" href="{% static 'css/contabilidad/facturas.css' %} ">
    <link rel="stylesheet" href="{% static 'css/fundacion/dashboard-facturas.css' %} ">
{% endblock script_css %}
{% block body %}
<span class="pagina-activa" data-pagina="facturas" hidden></span>
<div class="canva">
    <nav class=" secciones-facturas">
        <span class="seleccionado" data-pagina="facturas-pendientes">Facturas pendientes</span>
        <span class="" data-pagina="facturas-pagadas">Facturas pagadas</span>
    </nav>
    <section class="secciones facturas-pendientes">
        {% for factura in facturas %}
            {% if factura|total:"" > 0 %}
                {% include 'includes/facturas.html' %}
            {% endif %}
        {% endfor %}
    </section>
    <section class="secciones facturas-pagadas" style="display:none">
        {% for factura in facturas %}
            {% if factura|total:"" <= 0 %}
                {% include 'includes/facturas.html' %}
            {% endif %}
        {% endfor %}
    </section>
</div>
{% endblock %}

{% block script_js %}
    <script src="{% static 'js/fundacion/dashboard-facturas.js' %}"></script>
{% endblock script_js %}

fundacion/templates/pages/dashboard-farmacia.html
{% extends 'pages/base_fundacion.html' %}
{% load static %}
{% block script_css %}
    <link rel="stylesheet" href="{% static 'css/fundacion/farmacia/dashboard_farmacia.css' %}">
{% endblock script_css %}
{% block body %}
<span class="pagina-activa" data-pagina="farmacia" hidden></span>
    <section class="seccion-principal">
        <article class="medicamentos-pendientes">
            <h5>Tratamientos Pendientes</h5>
            <table class="table tabla-medicamentos">
                <thead>
                    <tr>
                        <th>Cliente</th>
                        <th>medicamento</th>
                        <th>dosis</th>
                        <th>Descripcion</th>
                        <th>Cantidad</th>
                        <th>Precio</th>
                        <th>Fecha</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                
                    {% for tratamiento in tratamientos %}
                    
                    {% if tratamiento.estado == 1 %}
                        <tr>
                            <td>{{tratamiento.id_ficha.id_expediente.id_datosPersonales.get_nombreCompleto}}</td>
                            <td>{{tratamiento.medicamento.nombre}}</td>
                            <td>{{tratamiento.medicamento.dosis}}</td>
                            <td>{{tratamiento.descripcion}}</td>
                            <td>{{tratamiento.cantidad}}</td>
                            <td>{{tratamiento.medicamento.precio}}</td>
                            <td>{{tratamiento.fecha}}</td>
                            <td>
                                <form class="form-tratamiento elementos-inline" action="{% url 'fundacion:actualizar-tratamiento' tratamiento.id_tratamiento %}" method="post">
                                {% csrf_token %}
                                <input class="cantidad"  name="cantidad" id="cantidad" value="{{tratamiento.cantidad}}" type="number">
                                <select class="btn" name="estado" id="estado">
                                    <option value="1">Pendiente</option>
                                    <option value="2">Entregado</option>
                                    <option value="3">Sin existencia</option>
                                    <option value="4">No se presento</option>
                                </select>
                                    <button class="btn btn-ico" type="submit">
                                        <img src="{% static 'imagenes/check.svg' %}" alt="">
                                        <span>Confirmar</span>
                                        </button>
                                </form>
                            </td>
                         </tr>
                    {% endif %}
                        
                        
                    {% endfor %}
               
                </tbody>
            </table>
        </article>


        <article class="medicamentos-entregados">
            <h5>Tratamientos Entregados</h5>
            <table class="table tabla-medicamentos">
                <thead>
                    <tr>
                        <th>Cliente</th>
                        <th>medicamento</th>
                        <th>dosis</th>
                        <th>Descripcion</th>
                        <th>Cantidad</th>
                        <th>Precio</th>
                        <th>Fecha</th>
                        <th>Estado</th>
                    </tr>
                </thead>
                <tbody>
                
                    {% for tratamiento in tratamientos %}
                        <tr>
                            <td>{{tratamiento.id_ficha.id_expediente.id_datosPersonales.get_nombreCompleto}}</td>
                            <td>{{tratamiento.medicamento.nombre}}</td>
                            <td>{{tratamiento.medicamento.dosis}}</td>
                            <td>{{tratamiento.descripcion}}</td>
                            <td>{{tratamiento.cantidad}}</td>
                            <td>{{tratamiento.medicamento.precio}}</td>
                            <td>{{tratamiento.fecha}}</td>
                            <td>
                                
                                {% if tratamiento.estado == 2 %}
                                    Entregado
                                {% endif %}
                                    
                            </td>
                         </tr>
                    {% endfor %}
               
                </tbody>
            </table>
        </article>
    </section>
{% endblock body %}

fundacion/templates/pages/dashboard-laboratorio.html
{% extends 'pages/base_fundacion.html' %}
{% load static %}
{% block script_css %}
    <link rel="stylesheet" href="{% static 'css/fundacion/laboratorio/laboratorio.css' %} ">
{% endblock script_css %}
{% block body %}
<span class="pagina-activa" data-pagina="laboratorio" hidden></span>
    <section class="base">
            
        {% comment %} pagina de citas {% endcomment %}
        
        {% if solicitudesLaboratorio or laboratoriosPendientes %}
            <nav class="nav-top">
                <span class="seleccionado-top" data-pagina="solicitudes">Solicitudes</span>
                <span class=""  data-pagina="pendientes">Resultado pendiente</span>
                <span class=""  data-pagina="historial">Historial</span>
            </nav>
            {% include 'pages/laboratorio/laboratorios_diario.html' with solicitudesLaboratorio=solicitudesLaboratorio laboratoriosPendientes=laboratoriosPendientes %}
        {% endif %}
        
        {% if form %}
            {% include 'pages/forms.html' with form=form %}
        {% endif %}
            
        
    </section>
{% endblock body %}
{% block script_js %}
    <script src="{% static 'js/fundacion/dashboard-laboratorio.js' %}"></script>
{% endblock script_js %}

fundacion/templates/pages/forms.html
{% load crispy_forms_tags %}
{% load static %}
{% block script_css %}
    <link rel="stylesheet" href="{% static 'css/fundacion/form/forms.css' %} ">
{% endblock script_css %}
{% block body %}
    <article class="form">
        <h4>{{titulo}}</h4>
        <form action="" method="post">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button class="btn" type="submit">Guardar</button>
        </form>
    </article>
{% endblock body %}